elastic/support-diagnostics

- bin/es-plugin.properties
- bin/support-diagnostics.bat
- bin/support-diagnostics.ps1
- bin/support-diagnostics.sh
- package.json
This adds auth support to the diag plugin. 
Cookie and basic auth support is added to the bash script
basic auth support is added to the powershell script (cookie support may take much longer).
> Auth support

- bin/support-diagnostics.ps1
- bin/support-diagnostics.sh
> Changing hot_threads from 10 to 10000 to ensure that all threads are retrieved

- bin/support-diagnostics.ps1
- bin/support-diagnostics.sh
Sometimes it's useful especially when aliases have filter and/or routing.
> Adds _alias output to the diagnostic dump

- README.md
There was no link to the actual download area for this, and I ran into someone using the master.zip download link at the main repo page.
So I added this in to make it clear.
> Added link to the download section

- CONTRIBUTING.md
- src/main/resources/chains.yml
Added system commands for logstash and created a Contributing doc.
> Logstash system commands and Contributing doc

- pom.xml
- src/main/java/com/elastic/support/diagnostics/Diagnostic.java
- src/main/java/com/elastic/support/diagnostics/commands/VersionAndClusterNameCheckCmd.java
- src/main/java/com/elastic/support/util/RestExec.java
> Connection message fix

- README.md
- src/main/java/com/elastic/support/diagnostics/Diagnostic.java
Added instructions for overriding diag.yml settings.
> Fixed issue with diagnostic continuing after validation failures.

- README.md
- src/main/java/com/elastic/support/diagnostics/DiagnosticService.java
- src/main/java/com/elastic/support/diagnostics/commands/DiagVersionCheckCmd.java
Split creation into 2 discrete sequences to enhance readability.
> Modify REST client creation process.

- README.md
- src/main/java/com/elastic/support/config/BaseInputs.java
- src/main/java/com/elastic/support/config/Constants.java
- src/main/java/com/elastic/support/config/DiagConfig.java
- src/main/java/com/elastic/support/config/DiagnosticInputs.java
- src/main/java/com/elastic/support/diagnostics/chain/DiagnosticChainExec.java
- src/main/java/com/elastic/support/diagnostics/commands/BaseQueryCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/SystemCallsCmd.java
- src/main/java/com/elastic/support/scrub/ScrubApp.java
Removed validate from BaseInputs, and Scrub app. 
Modified DiagnosticInputs to remove timed execution checks. 
Removed reps, intervals properties from DiagnosticInputs. 
Added IPv6 localhost to Constants for local address check. 
Minor extraneous code removed from DiagConfig and DiagnosticChainExec. 
BaseQueryCmd uses iterator to remove entries now that timed runs are gone and the config does not need to be reused. 
In system calls, when encountering error or unknown/unsupported OS just bypass calls altogether with logged message. 
Add proxy server doc to README.
> Minor changes suggested in last review

- src/main/java/com/elastic/support/diagnostics/DiagnosticService.java
- variable was being set with diagnostic version check bypass
> Fix Host Name Verification Bypass

- pom.xml
- src/main/java/com/elastic/support/config/BaseInputs.java
Fix JCommander variable assignment in BaseInputs
> Fix help options

- src/main/resources/diags.yml
Collect information that's necessary to troubleshoot ILM issues.
Closes https://github.com/elastic/support-diagnostics/issues/271
> Collect ILM information

- scripts/scrub.bat
- scripts/scrub.sh
Fix the packages in SH & BAT scripts
> Wrong package path to ScrubApp

- src/main/java/com/elastic/support/rest/RestClientBuilder.java
This commit resolves the following issues with PKI keystores.
- The keystore file is validated to see whether it exists, but the
check was backwards, and it would fail if the file _did_ exist.
- The error message printed '{}' rather than the path of the file.
- We would throw a NPE if the keystore password wasn't provided.
- The keystore was loaded after the SSL context was already built so
it was not actually used by the client.
Note: Since f4911c19, the keystore file is now validated even if the
keystore password is not provided. Previously the keystore was
silently ignored if there was no password option. This is change is
arguably a good thing, but it means users who previously might have
had their invalid "--keystore /some/random/file" ignored, now receive
an error, so we need to …
> Fix handling of PKI keystore

- src/main/java/com/elastic/support/config/Version.java
- src/main/java/com/elastic/support/diagnostics/DiagnosticService.java
- src/main/java/com/elastic/support/diagnostics/chain/DiagnosticContext.java
- src/main/java/com/elastic/support/diagnostics/commands/BaseQueryCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/HostIdentifierCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/RunClusterQueriesCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/UserRoleCheckCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/VersionCheckCmd.java
- src/main/java/com/elastic/support/util/SystemUtils.java
- src/main/resources/chains.yml
- src/test/java/com/elastic/support/test/TestConfigureElasticRestCalls.java
New command to check user for admin or superuser role, depending on version.
Version class added to handle major/minor/patch comparisons.
More explicit message and earlier exit if ES version could not be obtained.
> Add check for sufficient privileges to run diag.

- pom.xml
- src/main/java/com/elastic/support/diagnostics/DiagnosticService.java
- src/main/java/com/elastic/support/diagnostics/commands/UserRoleCheckCmd.java
- src/test/java/com/elastic/support/test/TestUserRoleCheck.java
> Fix branch

- pom.xml
* Update Jackson for latest security fix.
* Update next release number
> POM version updates

- src/main/java/com/elastic/support/diagnostics/chain/DiagnosticContext.java
- src/main/java/com/elastic/support/diagnostics/commands/CollectLogsCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/HostIdentifierCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/SystemCallsCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/SystemDigestCmd.java
- src/main/resources/chains.yml
Closes #294 
Modified check for hostname and pid to fix issue where hostname was not always used to determine which node to get pid and location.
> Host identifier fix

- README.md
- src/main/java/com/elastic/support/diagnostics/DiagnosticService.java
- src/main/java/com/elastic/support/monitoring/MonitoringExportConfig.java
- src/main/java/com/elastic/support/monitoring/MonitoringExportInputs.java
- src/main/java/com/elastic/support/monitoring/MonitoringExportService.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportProcessor.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportService.java
- src/main/java/com/elastic/support/util/ArchiveUtils.java
- src/main/resources/diags.yml
- src/main/resources/extract/cluster_ids.json
- src/main/resources/extract/general.json
- src/main/resources/extract/index_all.json
- src/main/resources/extract/index_stats.json
- src/test/java/com/elastic/support/monitoring/TestExportInputValidation.java
Last set of revisions:
* Adding additional feedback messages to confirm longer running processes are continuing.
* Some renaming and reshuffling.
* Unit tests for extract input validation
* Removed offset from inputs and force all to UTC
* Move from stopDate as input designation marker to startDate
* Additional feedback during scrolling and indexing to keep track of longer running jobs.
* Revisions to README
* Removed some extraneous log statements
> Additional Changes

- src/main/java/com/elastic/support/diagnostics/commands/SystemCallsCmd.java
- src/test/java/com/elastic/support/diagnostics/commands/TestJdkPathParsing.java
- src/test/resources/darwin-process-list.txt
Adjusted index position for JDK in process entry.
Adjusted unit tests.
> OSX JDK Parsing fix

- README.md
- pom.xml
- src/main/java/com/elastic/support/monitoring/MonitoringExportInputs.java
- src/test/java/com/elastic/support/monitoring/TestExportInputValidation.java
Fixed issues with default date and time. 
Updated documentation.
> Datetime validation fix.

- pom.xml
- src/main/java/com/elastic/support/ElasticClientService.java
- src/main/java/com/elastic/support/rest/RestClientBuilder.java
Needed to adjust the connection factory configuration - adding connection pooling broke bypassing verification in the last updates.
> Fix for issue with --noVerify not working.

- src/main/resources/diags.yml
Enrich processor is going to be released as part of the 7.5 release.
> Include enrich stats and get enrich policies endpoints.

- src/main/java/com/elastic/support/diagnostics/commands/GenerateManifestCmd.java
Modified call in manifest command to get DateTime instead of just date.
> Time restored to Manifest Date

- src/main/java/com/elastic/support/diagnostics/chain/DiagnosticChainExec.java
- src/main/java/com/elastic/support/diagnostics/chain/DiagnosticContext.java
- src/main/java/com/elastic/support/diagnostics/commands/ElasticVersionCheckCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/RunClusterQueriesCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/RunLogstashQueriesCmd.java
- src/main/java/com/elastic/support/diagnostics/commands/UserRoleCheckCmd.java
- src/main/java/com/elastic/support/rest/RestEntryFactory.java
List changed to map in order to facilitate getting individual calls.
Renamed VersionCheck to ElasticVersionCheck
> Rest Call config change

- src/main/java/com/elastic/support/scrub/ScrubService.java
Fix issue where whole output directory was deleted instead of just temp.
> Scrub Dir fix

- src/main/java/com/elastic/support/monitoring/MonitoringExportApp.java
- src/main/java/com/elastic/support/monitoring/MonitoringExportService.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportApp.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportInputs.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportProcessor.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportService.java
* Fixed issue with cluster name not being updated in imported indices
* Fixed validation issue with input clustername
* Modified Service Objects in export/import to be threadsafe.
> Fix Clustername Modification

- src/main/java/com/elastic/support/scrub/ScrubApp.java
- src/main/java/com/elastic/support/scrub/ScrubInputs.java
- src/main/java/com/elastic/support/scrub/ScrubService.java
Modifications to temp directory generation and cleanup.
Fix for regression:
Closes #316
> Fix to working dir delete

- pom.xml
- src/main/java/com/elastic/support/diagnostics/DiagnosticInputs.java
- src/main/java/com/elastic/support/rest/ElasticRestClientInputs.java
- src/main/java/com/elastic/support/rest/ElasticRestClientService.java
- src/main/java/com/elastic/support/rest/RestClientBuilder.java
- src/test/java/com/elastic/support/monitoring/TestExportInputValidation.java
Fixed issue with rest client proxy settings.
Fixed issue with default type for input class.
> Pre-release fixes

- pom.xml
- src/main/java/com/elastic/support/Constants.java
- src/main/java/com/elastic/support/diagnostics/chain/DiagnosticChainExec.java
Manifest generation calls replaced 
Update diag version.
Closes #343
> Manifest Missing

- pom.xml
- src/main/java/com/elastic/support/monitoring/MonitoringImportInputs.java
> Fixed issue with validation failing when no index name supplied.

- src/main/java/com/elastic/support/diagnostics/commands/CheckElasticsearchVersion.java
- src/main/java/com/elastic/support/diagnostics/commands/RunLogstashQueries.java
Fixed issue where Logstash rest configuration was not loaded.
Closes #348
> Logstash queries not loaded

- src/main/java/com/elastic/support/BaseConfig.java
- src/main/java/com/elastic/support/BaseInputs.java
- src/main/java/com/elastic/support/diagnostics/DiagnosticInputs.java
- src/main/java/com/elastic/support/monitoring/MonitoringExportInputs.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportInputs.java
- src/main/java/com/elastic/support/rest/ElasticRestClientInputs.java
- src/main/java/com/elastic/support/scrub/ScrubInputs.java
- src/main/resources/diags.yml
- src/main/resources/elastic-rest.yml
Unified toString conventions across inputs classes.
Modified for consistent commenting to id input related fields.
Fixed typo in diagnostic type error message
cat_master was outputting json - duplicate of another non-cat call. Removed json parameter.
Github settings for diagnostic version check changed to internal, but left option to mod if something changes. Only set if config is empty.
> PR related mods

- scripts/diagnostics.bat
- scripts/diagnostics.sh
- scripts/export-monitoring.bat
- scripts/export-monitoring.sh
- scripts/import-monitoring.bat
- scripts/import-monitoring.sh
- scripts/scrub.bat
- scripts/scrub.sh
Allow run of utility from directory outside the unzipped diagnostic directory.
> Allow run from outside install directory

- src/main/resources/elastic-rest.yml
Calls for ml_dataframes
Calls  for transform
> Additional Rest Calls

- src/main/java/com/elastic/support/diagnostics/commands/CollectDockerInfo.java
- src/main/java/com/elastic/support/diagnostics/commands/CollectSystemCalls.java
- src/main/resources/diags.yml
Run system calls on host system
Add inspect to container calls
> Additions for docker containers

- docker/Dockerfile
- docker/diagnostic-container-exec.sh
- scripts/docker-build.sh
- src/main/assembly/assembly.xml
- src/main/java/com/elastic/support/BaseConfig.java
- src/main/java/com/elastic/support/BaseInputs.java
- src/main/java/com/elastic/support/diagnostics/DiagnosticInputs.java
- src/main/java/com/elastic/support/diagnostics/DiagnosticService.java
- src/main/java/com/elastic/support/monitoring/MonitoringExportInputs.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportInputs.java
- src/main/java/com/elastic/support/rest/ElasticRestClientInputs.java
- src/main/java/com/elastic/support/scrub/ScrubInputs.java
- src/main/java/com/elastic/support/util/SystemUtils.java
- src/test/java/com/elastic/support/diagnostics/TestDockerAwareness.java
- src/test/resources/proc/1/cgroup-no
- src/test/resources/proc/1/cgroup-yes
Check for docker artifacts in base input class.
Resets output dir to default volume
Removes local run options.
Docker build script
Dockerfile
Sample docker container run
Fix for GH option check.
> Docker Container Awareness

- src/main/java/com/elastic/support/Constants.java
- src/main/java/com/elastic/support/diagnostics/DiagnosticApp.java
- src/main/java/com/elastic/support/diagnostics/DiagnosticInputs.java
- src/main/java/com/elastic/support/monitoring/MonitoringExportApp.java
- src/main/java/com/elastic/support/monitoring/MonitoringExportInputs.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportApp.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportInputs.java
- src/main/java/com/elastic/support/rest/ElasticRestClientInputs.java
- src/main/java/com/elastic/support/scrub/ScrubApp.java
- src/main/java/com/elastic/support/scrub/ScrubInputs.java
Added interactive mode to scrub
Cleaned up extraneous debug code.
> Scrub Interactive

- pom.xml
- src/main/java/com/elastic/support/Constants.java
- src/main/java/com/elastic/support/diagnostics/DiagnosticService.java
- src/main/java/com/elastic/support/diagnostics/commands/CollectDockerInfo.java
- src/main/java/com/elastic/support/util/LocalSystem.java
- src/main/java/com/elastic/support/util/RemoteSystem.java
- src/main/java/com/elastic/support/util/SystemCommand.java
- src/main/resources/diags.yml
Check different executable locations for presence of Docker executable.
closes #380
> Check Docker Paths

- src/main/java/com/elastic/support/BaseConfig.java
- src/main/java/com/elastic/support/diagnostics/commands/CheckDiagnosticVersion.java
GH is now sending a 404 if you do not use the complete url in the GET method. Modified the input for the full URL and modified the version check slightly.
> Github Query Fix

- src/main/java/com/elastic/support/diagnostics/ProcessProfile.java
- src/main/java/com/elastic/support/diagnostics/commands/CheckPlatformDetails.java
- src/main/java/com/elastic/support/rest/RestClient.java
Added caching to credentials for possible resubmit issue.
Made auth scope more lenient
> Authentication failure

- README.md
- pom.xml
- src/main/java/com/elastic/support/BaseConfig.java
- src/main/java/com/elastic/support/BaseInputs.java
- src/main/java/com/elastic/support/diagnostics/DiagnosticApp.java
- src/main/java/com/elastic/support/diagnostics/ShowHelpException.java
- src/main/java/com/elastic/support/diagnostics/commands/CollectDockerInfo.java
- src/main/java/com/elastic/support/monitoring/MonitoringExportApp.java
- src/main/java/com/elastic/support/monitoring/MonitoringImportApp.java
- src/main/java/com/elastic/support/rest/ElasticRestClientInputs.java
- src/main/java/com/elastic/support/scrub/ScrubApp.java
- src/main/java/com/elastic/support/util/ResourceCache.java
- src/main/java/com/elastic/support/util/SystemUtils.java
Modify Interactive mode to only prompt for after determining whether to use Basic or PKI auth to prevent user id from failing PKI call.
Fixes #401 
Fixes # 395
Fixes #393
> PKI Prompt Sequence Chage

- pom.xml
- src/main/java/com/elastic/support/BaseConfig.java
- src/main/java/com/elastic/support/diagnostics/commands/CollectDockerInfo.java
Remove other kubernates check related calls.
> Remove Kubernates checks

- src/main/resources/elastic-rest.yml
This PR should cover most of the APIs returning indices to include hidden indices.
Solves https://github.com/elastic/support-diagnostics/issues/416
> Support hidden indices

- src/main/resources/elastic-rest.yml
adds `GET _ml/datafeeds/_stats?pretty` API
closes https://github.com/elastic/support-diagnostics/issues/426
> Adds datafeeds stats calls

- pom.xml
- src/main/resources/scrub.yml
Adjusted scrub.yml
Fixed type in clusterName token.
> Release adjustments

- README.md
Modified and added scrub examples
> Doc Changes

- README.md
Temporarily rollback changes to README because of release upload issues.
> Rollback README due to deployment issues.

- README-BETA.md
- src/main/resources/diags.yml
Added Readme for beta.
Commenting for diags.yml, removal of unused settings
> Prep for beta release.

- README.md
Added a link under the Support Diagnostics Utility heading to the latest version
> Add link to the latest version of the diagnostic

- src/main/resources/elastic-rest.yml
Resolves https://github.com/elastic/support-diagnostics/issues/467.
> mapping/cluster state: remove pretty

- src/main/resources/elastic-rest.yml
Closes https://github.com/elastic/support-diagnostics/issues/472
> Add Autoscaling Capacity API

- README.md
This pulls the changes from https://github.com/elastic/support-diagnostics/pull/455 to a single commit without all of the undesired commits.
> [README] Fix Typos / Add Highlighting

- README.md
fixes https://github.com/elastic/support-diagnostics/issues/500
> fix `clustername` in the Readme examples

- CONTRIBUTING.md
- NOTICE.txt
- pom.xml
- src/main/java/co/elastic/support/diagnostics/commands/CollectKibanaLogs.java
- src/main/java/co/elastic/support/diagnostics/commands/KibanaGetDetails.java
This makes the changes needed to prepare the code for release in Maven Central. (It was used to successfully create the SNAPSHOT there already)
Note: Code changes were only on invalid Javadoc.
> [Maven] Prepare Release

- CONTRIBUTING.md
- pom.xml
This also increments the version from the deployed version.
> [Maven] Add more details for post-deploy

- NOTICE.txt
- pom.xml
This marks the release version for 8.2.1.
> Release 8.2.1

- pom.xml
This prepares for the next set of code changes.
> Increment Version for next release

- pom.xml
> Update snakeyaml to 1.29

- pom.xml
> Update commons-compress to 1.21

- pom.xml
> Update jackson-databind to 2.12.5

- pom.xml
> Update httpclient to 4.5.13

- pom.xml
This increments the version to 8.2.3-SNAPSHOT.
> Prepare 8.2.3

- src/main/resources/elastic-rest.yml
👋🏼 adds Elasticsearch API's
- [GET _slm/status](https://www.elastic.co/guide/en/elasticsearch/reference/current/slm-api-get-status.html) (frequent)
- [GET _logstash/pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/current/logstash-api-get-pipeline.html) (sanity checked whenever pipelines discussed but less frequent)
> +frequent ES API queries

- pom.xml
> [Release] 8.2.3

- pom.xml
This updates the version to prepare for future changes.
> 8.2.4-STAGING

- pom.xml
> [Dependency] Upgrade log4j2

- pom.xml
This also increments the version to prepare for a release.
> [Dependency] Upgrade Log4j2 again

- pom.xml
This upgrades log4j2 dependency to 2.17.0
> [Dependency] Upgrade Log4j2 to 2.17.0

- pom.xml
> [Release] 8.2.6

- src/main/resources/elastic-rest.yml
`_cat/aliases` sometimes can be as extensive as `_cat/indices` and hard to read when it's not sorted.
This PR adds sorting to the `_cat/aliases` results by alias and then index name starting from 5.1.1 when the sort was added under https://github.com/elastic/elasticsearch/pull/20658
<details>
<summary>Before - /_cat/aliases?v</summary>
```
alias                                                               index                                                                                 filter routing.index routing.search is_write_index
apm-7.17.0-span                                                     apm-7.17.0-span-000001                                                                -      -             -              true
.kibana-event-log-7.16.0 …
```
> Add sort in the _cat/aliases request

- src/main/java/co/elastic/support/diagnostics/commands/CheckKibanaVersion.java
- src/test/java/co/elastic/support/diagnostics/commands/TestCheckKibanaVersion.java
> Read Kibana version from /api/stats instead of /api/settings

- src/main/resources/kibana-rest.yml
Kibana URI `/api/status` returns the JSON version of this `/status` UI view which is helpful to troubleshoot [plugin](https://www.elastic.co/guide/en/kibana/current/kibana-plugins.html) health. 
I'm only able to trace endpoint availability back to v6.5.0 when code was migrated to Kibana repo [here](https://github.com/elastic/kibana/blob/main/src/core/server/status/routes/integration_tests/status.test.ts#L35). Originally surfaced [here](https://discuss.elastic.co/t/kibana-healthcheck-page/70959/2). Response body changed in 8.0 [here](https://github.com/elastic/kibana/pull/76054) & future discussed here https://github.com/elastic/kibana/issues/46984.
```
{"name":"947ae8ac6d96","uuid":"3fd640a5-0caf-43d2-8ac2-5b443d03c7f4","version":{"number":"8.1.2","build_hash":"0f6d770b4febdce2134bcadc3495 …
```
> Add Kibana Status API

- src/main/resources/elastic-rest.yml
The changes should allow to see ILM failures for system/hidden indices.
> Allows to see ILM failures for hidden and system indices

- src/main/java/co/elastic/support/diagnostics/commands/RunKibanaQueries.java
Attempt to fix https://github.com/elastic/support-diagnostics/issues/599
> Fix pagination to be more readable and also include last page

- src/main/resources/elastic-rest.yml
Depends on https://github.com/elastic/elasticsearch/pull/92879
> Rename health API from /_health to /_health_report

- README.md
Added an example of extracting monitoring data from the elastic cloud. This should reduce the round trips to get the data out of that - or elastic cloud enterprise environments.
> monitoring data extraction from elastic cloud

- src/main/resources/diags.yml
> [626] filter plain text and json logs

- pom.xml
- src/main/java/co/elastic/support/diagnostics/chain/DiagnosticChainExec.java
- src/main/java/co/elastic/support/diagnostics/commands/GenerateLogstashDiagnostics.java
- src/main/resources/logstash-diagnostic-templates/flow_metrics.html.ftlh
In 8.5-8.7, the Logstash team introduced and then expanded Flow Metrics in the Logstash node stats API, which means they are already available as part of capture from this tool. Flow metrics give us current, recent, and lifetime flow rates for many meaningful metrics, allowing us to compare a pipeline or process's current behavior to itself over time.
Currently, the support diagnostics Analyzer does not yet incorporate Flow Metrics and still requires two-spaced captures to provide meaningful rate-of-flow insights. Additionally, the as-presented rate-of-flow metrics in the analyzer tool are not standardized or cohesive (mixing units or mixing wall-clock vs CPU clock)
We want to create a new diagnostic template, embedded in this support-diagnostics tool that includes process-, pipeline-, …
> [Logstash] Create a new diagnostic template based on the flow metrics

- src/test/java/co/elastic/support/diagnostics/TestDiagnosticService.java
> reducing test concurrency

- src/main/resources/kibana-rest.yml
Reverts elastic/support-diagnostics#658
> Revert "Add Fleet Health Check"

- NOTICE.txt
- pom.xml
> [Dependency] Upgrade commons-compress

- src/main/resources/elastic-rest.yml
👋🏽  May we kindly account for https://github.com/elastic/elasticsearch/issues/88752
Confirmation
- <img width="742" alt="image" src="https://github.com/elastic/support-diagnostics/assets/26751266/a45c5412-63bc-41be-95a1-e4fdafc2ba56">
- <img width="745" alt="image" src="https://github.com/elastic/support-diagnostics/assets/26751266/1dd9951d-ea0a-4ce7-a95e-5644ea782cd4">
> (ES)(Index Stats) Account for Closed Indices

- .dockerignore
- Dockerfile
- docker-build.sh
- docker-run.sh
- scripts/diagnostics.bat
- scripts/diagnostics.sh
- scripts/export-monitoring.bat
- scripts/export-monitoring.sh
- scripts/import-monitoring.bat
- scripts/import-monitoring.sh
- scripts/scrub.sh
- src/main/java/co/elastic/support/scrub/ScrubInputs.java
This changes the Docker build to run with Wolfi (and tests).
The downside to this change is that it requires that we build the Docker image.
> [Docker] Use Wolfi

- src/main/resources/elastic-rest.yml
> Add new option include_remotes for cluster/stats

- src/main/java/co/elastic/support/diagnostics/chain/DiagnosticChainExec.java
-> no change in API requests, just added the same set to `logstash-api` type diagnostics.
fixes #792
> logstash-flow-metrics added for logstash-api diag

- scripts/share_ad_job_state/README.md
- scripts/share_ad_job_state/export_model_snapshot.py
- scripts/share_ad_job_state/import_model_snapshot.py
- scripts/share_ad_job_state/tests/test_export_model_snapshot.py
- scripts/share_ad_job_state/tests/test_import_model_snapshot.py
- Added support for saving notifications and improved date handling in export_model_snapshot.py.
- Refactored input data handling and error management in import_model_snapshot.py.
- Updated tests to validate new features and error handling.
> Enhance export and import model snapshot functionality

- src/main/resources/elastic-rest.yml
Fixes https://github.com/elastic/support-diagnostics/issues/902
> Add ML Inference Endpoint to elastic-rest.yaml
