README.md
I noticed when running this that the "port" example needed an extra -.  Simple change.
=> Updated --port typo in README

scripts/diagnostics.bat
For properly dealing with parenthesis in JAVA_HOME, for instance `C:\Program Files (x86)\Java\jdk1.8.0_74`.
See https://blogs.msdn.microsoft.com/oldnewthing/20060823-00/?p=29993 for details.
Also looks like `DIAG_JAVA_OPTIONS` was used improperly (`DIAG JAVA_OPTIONS` instead).  Note the space rather than underscore.
=> Enabled delayed expansion and fix use of DIAG_JAVA_OPTIONS

src/main/resources/diags.yml
This commit adds a call to the jps command to the diagnostics output for
inspection of the parameters used to start the Elasticsearch JVM.
=> Add jps to diagnostics output

src/main/java/com/elastic/support/diagnostics/commands/SystemCallsCmd.java, src/main/resources/diags.yml
Having the output from jstack in diagnostics dumps would be incredibly helpful so this commit adds that.
=> Add jstack to diagnostics dump

src/main/java/com/elastic/support/diagnostics/commands/RunClusterQueriesCmd.java
Today if the diagnostics tool is run against a major version that it does not support it throws a null pointer exception and does not really reveal what the problem is. This commit traps this situation and provides a helpful error message to the user.
Additionally, the logic for parsing the major version is broken as it will fail when the major version has two digits. This commit fixes this situation too.
=> Throw helpful error message on unsupported major

src/main/java/com/elastic/support/diagnostics/commands/LogAndConfigCmd.java
Assuming that the GC logs are available in the log directory (as they will be by default starting in 6.2.0), this commit brings all available GC logs back in the diagnostics bundles. Future refinements can handle cases when the GC logs are in another location.
Relates elastic/elasticsearch#27610
=> Bring GC logs by default

src/main/java/com/elastic/support/diagnostics/commands/SecurityPropertiesCmd.java, src/main/resources/chains.yml, src/main/resources/security-properties.txt
This commit adds support for reading system security properties in a diagnostics dump and now dumps the positive and negative DNS cache settings from the system security policy.
=> Dump network address cache security properties

src/main/resources/diags.yml
Most of the urls lack leading slashes, tidying things up so that's the same everywhere.
=> Remove leading slashes

src/main/resources/diags.yml
This adds the `s=index` parameter for 5.2+ clusters for these APIs:
```
_cat/indices
_cat/segments
_cat/shards
```
Sorting by index helps to make the separate files more consistent and easier to read by humans.
=> Sort _cat APIs by index

src/main/resources/diags.yml
CCR is going to be GA from 6.7, so it is time to include some of its endpoints in the diagnostic tool.
=> Include ccr info, stats and auto follow pattern endpoints.

README.md, src/main/java/com/elastic/support/diagnostics/commands/DiagVersionCheckCmd.java
Current behavior prompts user on whether to continue, but it will continue no matter which they select. Since exiting can be problematic change message to an alert that the diag is out of date, display the URL to the current version, and then stop. The user will then need to press Enter to continue.
=> Fix issue with misleading Diagnostic Version Check message.

pom.xml, src/main/java/com/elastic/support/diagnostics/DiagnosticService.java, src/main/resources/diags.yml
- removed verbose parameter from segments to prevent Elasticsearch exceptions on large clusters generating over 2G of output.
- increased connection and socket read  timeouts in REST calls.
- changed configuration units to seconds rather than milliseconds.
=> Stability Related Configuration Adjustments

src/main/resources/diags.yml, src/test/resources/diags-test.yml
We do not need to `ss` to resolve service names and we would like to see all sockets.
Add `-an` to (from the man page):
* `-a` Display both listening and non-listening (for TCP this means established connections) sockets.
* `-n` Do not try to resolve service names.
Also removed the command from MacOS as it does not exist there.
=> ss command flag changes

src/main/java/com/elastic/support/rest/RestClientBuilder.java
Updates cookie spec used to the more lenient 6265. Default will not change until next major version. Causes issues when run through some load balancers.
Closes: #233
=> Update Cookie Spec

src/main/java/com/elastic/support/config/Constants.java, src/main/java/com/elastic/support/diagnostics/DiagnosticApp.java, src/main/java/com/elastic/support/diagnostics/DiagnosticException.java, src/main/java/com/elastic/support/diagnostics/DiagnosticService.java, src/main/java/com/elastic/support/diagnostics/chain/Chain.java, src/main/java/com/elastic/support/diagnostics/chain/DiagnosticChainExec.java, src/main/java/com/elastic/support/diagnostics/commands/BaseQueryCmd.java, src/main/java/com/elastic/support/diagnostics/commands/RunClusterQueriesCmd.java, src/main/java/com/elastic/support/diagnostics/commands/RunLogstashQueriesCmd.java, src/main/java/com/elastic/support/diagnostics/commands/VersionCheckCmd.java, src/main/java/com/elastic/support/rest/RestResult.java
Closes #293 
* Reworked error handling, moving some of the logging and checking down to the result level from the BaseQuery and changing the command execution to break out of the chain execution on a fatal error, such as a bad version check call. Add specific error codes to display in order to flag a bad login at the command line.
=> Id auth errors

README.md, src/main/java/com/elastic/support/BaseService.java, src/main/java/com/elastic/support/config/ScrubInputs.java, src/main/java/com/elastic/support/scrub/ScrubApp.java, src/main/java/com/elastic/support/scrub/ScrubProcessor.java, src/main/java/com/elastic/support/scrub/ScrubService.java, src/main/java/com/elastic/support/util/ArchiveUtils.java, src/main/java/com/elastic/support/util/SystemUtils.java
Fixed issue where Strings longer than 32 characters generated an error during token replacement.
Added option to obfuscate a single file rather than a full diagnostic archive.
Closes #301 , #302
=> Fix 32 byte character limit on obfuscation.

src/main/resources/diags.yml
In preparation for Snapshot Lifecycle Management shipping in 7.4.0,
collect information that will be useful and/or necessary to troubleshoot
SLM issues.
=> Collect SLM information

pom.xml, src/main/java/com/elastic/support/config/Constants.java, src/main/java/com/elastic/support/rest/RestEntry.java, src/main/java/com/elastic/support/rest/RestEntryBuilder.java, src/main/resources/elastic-rest.yml, src/main/resources/log4j2.xml, src/main/resources/logstash-rest.yml, src/test/java/com/elastic/support/version/TestRestConfigFileValidity.java, src/test/resources/log4j2-test.xml
Dependency and version updates.
Minor mods to logging config.
Separated out rest calls to elastic and logstash specific and changed versioning format from release based to call based.
Added test to validate format of rest configuration files at build time.
New classes for refactored rest entries.
Closes #326 , #277
=> Configuration move to semver -centric version checks for queries.

src/main/java/com/elastic/support/diagnostics/commands/CheckElasticsearchVersion.java, src/main/java/com/elastic/support/monitoring/MonitoringExportConfig.java, src/main/java/com/elastic/support/monitoring/MonitoringExportService.java, src/main/java/com/elastic/support/monitoring/MonitoringImportConfig.java, src/main/java/com/elastic/support/monitoring/MonitoringImportProcessor.java, src/main/java/com/elastic/support/monitoring/MonitoringImportService.java, src/main/resources/diags.yml
Versioned queries to allow adding legacy hits handling for v7 urls.
Went to separate import configuration object rather than use a shared one for import and export
Exposed the functionality to get ES version and create semver object.
Closes #339
=> Fix for v5 export issues

scripts/diagnostics.bat, scripts/diagnostics.sh, scripts/export-monitoring.bat, scripts/export-monitoring.sh, scripts/import-monitoring.bat, scripts/import-monitoring.sh, scripts/scrub.bat, scripts/scrub.sh
Displays error message and exits if it cannot find the lib directory created when building the runtime distribution.
closes #203
=> Check for source distribution

pom.xml, src/main/java/com/elastic/support/diagnostics/chain/DiagnosticChainExec.java, src/main/java/com/elastic/support/diagnostics/commands/CheckPlatformDetails.java
Issue calls directly against input host when API used due to issues with Cloud, EDE, ECK clusters.
=> Bypass finding master for api type

pom.xml, src/main/java/com/elastic/support/diagnostics/commands/CheckPlatformDetails.java, src/main/java/com/elastic/support/diagnostics/commands/RunClusterQueries.java
User had http traffic from node where diag was run to host where master was installed blocked, which called all rest calls to fail. Sending all rest calls through the target node for now until ability to disable and get diagnostic data can be added.
=> Send calls to input node

pom.xml, src/main/java/com/elastic/support/util/ResourceCache.java
Check the input terminal for whether it was created with JLIne - if so suppress event handling to prevent the exclamation point from terminating the process.
Fixes #390
=> Exclamation Point Fix

src/main/java/com/elastic/support/BaseInputs.java
Similar symptoms as  https://github.com/elastic/support-diagnostics/pull/412 
Before this patch `validateDir` will never fail if any string is passed in
because `if (!file.exists() && file.isDirectory())` will never return ~false~ true ( it can't be a directory if it doesn't exist).
I can't reproduce the undesired behaviour this could cause, as there are several places this is called from, and I'm still getting my head around it.
Because of that, I would ask that someone who knows their way around this and can assess all the places it is used reviews this change.
I'll keep digging to see if I can come up with some concrete examples
[Edit: Sneaky ninja edit - this logic stuff is hard!]
=> Correct validation of existing directory

src/main/java/com/elastic/support/BaseInputs.java
Prior to this change, the user cannot specify a directory to be used for output, if the directory does not already exist.
The interactive text says:
"Fully qualified path to an output directory. If it does not exist the diagnostic will attempt to create it."
but the bit which does the creation if it doesn't exist `validateOutputDirectory`  is never called.
To see this behaviour pre-patch
Run the Scrub 
- Select Archive
- Select an archive file to scrub
- select a config file
- Select a non-existent directory for the output.
The scrubber should create this directory (assuming sufficient permissions etc.), but it fails with 
```
Invalid value.
Specified file could not be located.
```
and asks for the directory again.
=> Correct validation of non-existent output directory

src/main/java/com/elastic/support/BaseInputs.java
Before this patch `validateRequiredFile` will never fail if any string is passed in
because ` if (!file.exists() && file.isDirectory())` will never return ~false~ true ( it can't be a directory if it doesn't exist).
To see the first behaviour before this change:
- Run the Scrub in interactive mode
- Select Archive
- put in gibberish for the archive 
The script should fail with "Specified required file location could not be located", but it doesn't, it just carries on:
```
Select the type of file you wish to scrub.
1: Scrub Archive
2: Scrub Single File
Enter your choice: 1
Enter the full path of the archive you wish to import. sdadsadas
If you do not specify a yaml configuration file, the utility will automatically....
```
[Edit sneaky ninja edit to correct my own bug-raising logic! This …
=> Correct file validation logic

README.md
Fixes minor typos in the usage for the sanitisation tool in README.
=> README: fix typos in scrub.sh usage

src/main/resources/elastic-rest.yml
Add support for capturing the output from the new dangling indices API. This applies from 7.9.0 onwwards.
=> Add support for capturing dangling indices

README.md
I no longer see on top a section called "<some number> Releases" the readme refers to, simplifying by just specifying the link to the latest release
=> Fix downloading-and-installing readme section

src/main/resources/elastic-rest.yml
Elasticsearch 7.13.0 has a new Cache Stats API for Searchable Snapshots which provides various statistics about the shared cache (see elastic/elasticsearch#71701 and elastic/elasticsearch#71849).
This pull request adds this new API to the support diagnostics.
=> Add Searchable Snapshots Cache Stats API

src/main/java/com/elastic/support/BaseService.java, src/main/java/com/elastic/support/diagnostics/DiagnosticException.java, src/main/java/com/elastic/support/diagnostics/DiagnosticService.java, src/main/java/com/elastic/support/diagnostics/JavaPlatform.java, src/main/java/com/elastic/support/diagnostics/chain/Command.java, src/main/java/com/elastic/support/diagnostics/chain/DiagnosticChainExec.java, src/main/java/com/elastic/support/diagnostics/commands/CheckElasticsearchVersion.java, src/main/java/com/elastic/support/diagnostics/commands/CheckKibanaVersion.java, src/main/java/com/elastic/support/diagnostics/commands/KibanaGetDetails.java, src/main/java/com/elastic/support/diagnostics/commands/RunClusterQueries.java, src/main/java/com/elastic/support/diagnostics/commands/RunKibanaQueries.java, src/main/java/com/elastic/support/diagnostics/commands/RunLogstashQueries.java, src/main/java/com/elastic/support/monitoring/MonitoringExportService.java, src/main/java/com/elastic/support/scrub/ScrubService.java, src/main/java/com/elastic/support/util/ArchiveUtils.java, src/main/java/com/elastic/support/util/RemoteSystem.java, src/main/java/com/elastic/support/util/SystemUtils.java, src/test/java/com/elastic/support/diagnostics/commands/TestCheckKibanaVersion.java, src/test/java/com/elastic/support/diagnostics/commands/TestKibanaGetDetails.java, src/test/java/com/elastic/support/diagnostics/commands/TestRunKibanaQueries.java
We need to be able to use the diagnostic tool as a Java library as described in #485.
This PR makes 2 main changes:
1. `DiagnosticService#exec` and `ScrubService` should return `java.io.File` instead of `void`. This makes it easier for callers to know where the zip file was saved, otherwise they would need to list which files are present in the `outputDir` after the tool is finished.
2. `DiagnosticService#exec` and `ScrubService` should throw `DiagnosticException` instead of logging and swallowing errors. `DiagnosticException` is a `RuntimeException` which makes harder for consumers be aware of errors and catch them properly.
=> DiagnosticService and ScrubService should return File and throw checked Exception

src/main/java/com/elastic/support/diagnostics/commands/RetrieveSystemDigest.java, src/main/java/com/elastic/support/monitoring/MonitoringImportService.java, src/main/java/com/elastic/support/scrub/ScrubProcessor.java, src/main/java/com/elastic/support/util/ArchiveUtils.java, src/main/java/com/elastic/support/util/JsonYamlUtils.java, src/main/java/com/elastic/support/util/SystemUtils.java, src/test/java/com/elastic/support/diagnostics/commands/TestKibanaGetDetails.java, src/test/java/com/elastic/support/diagnostics/commands/TestRunKibanaQueries.java, src/test/java/com/elastic/support/rest/TestRestConfigFileValidity.java
Part of #485.
In many places `Closeable` instances such as `OutputStream`, `InputStream` and `Writer` weren't being closed properly in finally blocks. This may cause memory leaks if exceptions are thrown while writing/reading to those streams.
Tried to use try-with-resources as much as possible, only in few cases closing in finally blocks made sense.
=> Close streams properly

pom.xml
This is part of #485.
In order to use the diagnostic tool as a Java lib, all configuration files like `diags.yml`, `elastic-rest.yml`, etc, must exist in the classpath, otherwise calls to `JsonYamlUtils.readYamlFromClasspath(Constants.DIAG_CONFIG, true)` fail to load them.
I tested overriding values in `config/elastic-rest.yml` and it works as expected, that is, everything in `/config` take precedence over the same files in `support-diagnostics-*.jar`. Users will still be able to easily modify them without modifying the jar file, that's possible because of:
https://github.com/elastic/support-diagnostics/blob/6255ac5fdb1a45dfd5d2155a4d02af3cb7d5386f/scripts/diagnostics.sh#L31
Anything that comes first in `-cp` takes precedence over the ensuing paths.
=> Include *.yml files in jar file

src/main/java/com/elastic/support/diagnostics/commands/CheckUserAuthLevel.java, src/main/java/com/elastic/support/util/UrlUtils.java
This URL encodes the username when supplying it as part of the URL
(rather than as part of an auth header).
I tested this by creating a user named `temp\user`. Using the existing diagnostic fails as noted in the linked issue. After using the code in this branch, it works successfully.
Closes https://github.com/elastic/support-diagnostics/issues/489
=> URL Encode Username

src/main/java/com/elastic/support/diagnostics/DiagnosticService.java, src/main/java/com/elastic/support/diagnostics/JavaPlatform.java
In #486, I changed the order in which `createArchive` was called, leaving it outside the `finally` block.
This may be problematic because the zip fule won't be created if `DiagnosticChainExec.runDiagnostic` fails with a `DiagnosticException`.
I'm changing it back to make it work as it used to work, that is, exceptions should always be printed to console AND to the `diagnostics.log` file inside the zip file.
=> Should always create archive file when failures happen

pom.xml
This adds details required by Maven Central when not using a SNAPSHOT.
=> [Maven] Update POM with required details

src/main/java/co/elastic/support/BaseConfig.java, src/main/java/co/elastic/support/BaseInputs.java, src/main/java/co/elastic/support/diagnostics/DiagnosticService.java, src/main/java/co/elastic/support/diagnostics/commands/CheckDiagnosticVersion.java, src/main/java/co/elastic/support/diagnostics/commands/CheckElasticsearchVersion.java, src/main/java/co/elastic/support/diagnostics/commands/CheckKibanaVersion.java, src/main/java/co/elastic/support/monitoring/MonitoringExportService.java, src/main/java/co/elastic/support/monitoring/MonitoringImportService.java, src/main/java/co/elastic/support/rest/RestClient.java, src/test/java/co/elastic/support/diagnostics/TestDiagnosticService.java, src/test/java/co/elastic/support/diagnostics/commands/TestCheckKibanaVersion.java, src/test/java/co/elastic/support/diagnostics/commands/TestKibanaGetDetails.java, src/test/java/co/elastic/support/diagnostics/commands/TestRunKibanaQueries.java, src/test/java/co/elastic/support/rest/TestRestExecCalls.java
Add support to specify additional request headers to be passed when making API requests to the Elasticsearch server.
This is needed in some environments where custom headers may be required for authorization purposes, logging etc.
=> Add support for additional headers to DiagnosticService

src/main/java/co/elastic/support/BaseInputs.java, src/main/java/co/elastic/support/diagnostics/DiagnosticApp.java, src/main/java/co/elastic/support/diagnostics/DiagnosticInputs.java, src/main/java/co/elastic/support/diagnostics/DiagnosticService.java, src/main/java/co/elastic/support/diagnostics/chain/DiagnosticContext.java, src/main/java/co/elastic/support/diagnostics/commands/CheckElasticsearchVersion.java, src/main/java/co/elastic/support/diagnostics/commands/CheckKibanaVersion.java, src/main/java/co/elastic/support/diagnostics/commands/CheckPlatformDetails.java, src/main/java/co/elastic/support/diagnostics/commands/CheckUserAuthLevel.java, src/main/java/co/elastic/support/diagnostics/commands/CollectDockerInfo.java, src/main/java/co/elastic/support/diagnostics/commands/CollectKibanaLogs.java, src/main/java/co/elastic/support/diagnostics/commands/CollectLogs.java, src/main/java/co/elastic/support/diagnostics/commands/CollectSystemCalls.java, src/main/java/co/elastic/support/diagnostics/commands/KibanaGetDetails.java, src/main/java/co/elastic/support/diagnostics/commands/RunClusterQueries.java, src/main/java/co/elastic/support/diagnostics/commands/RunKibanaQueries.java, src/main/java/co/elastic/support/diagnostics/commands/RunLogstashQueries.java, src/main/java/co/elastic/support/monitoring/MonitoringExportApp.java, src/main/java/co/elastic/support/monitoring/MonitoringExportInputs.java, src/main/java/co/elastic/support/monitoring/MonitoringExportService.java, src/main/java/co/elastic/support/monitoring/MonitoringImportApp.java, src/main/java/co/elastic/support/monitoring/MonitoringImportInputs.java, src/main/java/co/elastic/support/rest/ElasticRestClientInputs.java, src/main/java/co/elastic/support/scrub/ScrubApp.java, src/main/java/co/elastic/support/scrub/ScrubInputs.java, src/main/java/co/elastic/support/util/ResourceCache.java, src/main/java/co/elastic/support/util/TextIOManager.java, src/test/java/co/elastic/support/diagnostics/TestDiagnosticService.java, src/test/java/co/elastic/support/diagnostics/commands/TestKibanaGetDetails.java, src/test/java/co/elastic/support/diagnostics/commands/TestRunKibanaQueries.java
This PR makes the library more multithreading-friendly, allowing concurrent executions of the diagnostic generation in the same process.
It achieves that by:
- making `ResourceCache` a non-global
- adding a separate `TextIOManager` which needs to be explicitly instantiated for interactive use cases
- allowing the exclusion of log files from the diagnostics, since those rely on global log4j settings which won't behave properly in a multithreading setting.
=> Fix multithreading

src/main/resources/elastic-rest.yml
i have included the s=index which i guess it was missing, and also fixed the double ampersand that didn't look good
=> double ampersand in cat_indices call

src/main/java/co/elastic/support/diagnostics/commands/CheckDiagnosticVersion.java
This trims the leading 'v' from the version number in the Git tag
so that the semver comparison works.
Closes https://github.com/elastic/support-diagnostics/issues/518
=> Trim 'v' from GitHub tag name

src/test/java/co/elastic/support/diagnostics/TestDiagnosticService.java
This makes it so the test runs without fetching local network interfaces, which are timing out the test on my local macOS install (likely due to some defunct USB network interfaces on my own machine).
=> Speed Up test

src/main/resources/elastic-rest.yml
This adds the new API that becomes available in 7.15.
Closes https://github.com/elastic/support-diagnostics/issues/521
=> Add "_snapshot" request for 7.15

src/main/java/co/elastic/support/BaseInputs.java, src/main/java/co/elastic/support/diagnostics/DiagnosticApp.java, src/main/java/co/elastic/support/diagnostics/DiagnosticInputs.java, src/main/java/co/elastic/support/monitoring/MonitoringExportApp.java, src/main/java/co/elastic/support/monitoring/MonitoringExportInputs.java, src/main/java/co/elastic/support/monitoring/MonitoringImportApp.java, src/main/java/co/elastic/support/monitoring/MonitoringImportInputs.java, src/main/java/co/elastic/support/rest/ElasticRestClientInputs.java, src/main/java/co/elastic/support/scrub/ScrubApp.java, src/main/java/co/elastic/support/scrub/ScrubInputs.java
This adds `@Override` to all `parseInputs` methods to guarantee that they're overriding the root implementation rather than serving as overloads that were going uninvoked.
The root failure of _not_ doing that was that inputs that required user inputs were not triggered (e.g., `-p`).
This also fixes a typo in the ScrubApp's version.
=> Add textIOManager to add parseInputs

src/main/resources/elastic-rest.yml
This adds the `nodes_shutdown_status` output for `/_nodes/shutdown`.
Closes https://github.com/elastic/support-diagnostics/issues/536
=> [ES] Add _nodes/shutdown API

src/main/resources/elastic-rest.yml
Adds API Request to [SSL Cert](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/security-api-ssl.html#security-api-ssl-example) which wouldn't catch ALL but would help to discern certificate `expiry` or expiration dates to compare to forwarded logs.
=> +SSL Cert API Request

src/main/resources/elastic-rest.yml
ILM explain created in 6.6, but starting 7.4 there's a `only_errors=true` flag which would help narrow down into erring ILM explains a lot faster for users.
🙏🏼 When users ask for help with ILM errors we get the entire ILM explain file which sometimes breaks out
- 1-2/100 have errors => search for string `"step" : "ERROR"`
- 99/100 have errors => if so, usually same root config issue & can kick out all at once
- 30/100 have errors => copy file, {Python JSON, manually} lookup to filter `ilm_explain.json` into a sub file `ilm_explain_errors.json` to actually work from.
In my today example, my Python script wasn't working for some reason, so I just manually narrowed in from 700 indices to 32 which took about 25mins.
=> +ilmExplainOnlyErrors

src/main/resources/elastic-rest.yml
[GeoIP stats endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/geoip-stats-api.html) has been included since 7.13.0 under https://github.com/elastic/elasticsearch/pull/70282
It gets download statistics for GeoIP2 databases used with the geoip processor, which is useful for troubleshooting.
Resolves https://github.com/elastic/support-diagnostics/issues/549
=> Add geoip stats API request

src/main/resources/elastic-rest.yml, src/test/java/co/elastic/support/rest/TestRestConfigFileValidity.java
The two ES endpoints related to transforms are not retrieved properly when the tool is used in library-mode. It turns out that they are the only ones missing a leading / in the configuration file `elastic-rest.yml`.
This PR adds the leading / and adds a related check to `TestRestConfigFileValidity.java`.
=> Add leading / to elastic rest endpoints which were missing it.

scripts/diagnostics.sh
This code fixes incorrect check for lib directory for `diagnostics.sh`
I also added double quotes for variables that contain a path to prevent globing and word splitting.
=> close #562 - fix message when running bash file from sources

src/main/resources/elastic-rest.yml
@pickypg @dakrone may we add the `GET _snapshot` request to the ES diag? Currently we return `GET _cat/repositories` but it doesn't include sub information used for troubleshooting SLM repositories. Not interpreting returned data as user private but kindly decline if it could return sensitive data. 🙏🏼
=> Add list SLM repositories

src/main/java/co/elastic/support/rest/RestEntryConfig.java
A user ran into this message `was bypassed due by version check` and asked me if this was of any concern.
I think the log type can be relaxed to `warn` perhaps?
=> changed  version check error message to warning.

src/main/java/co/elastic/support/diagnostics/commands/RunKibanaQueries.java
The use of the `JsonNode.toPrettyString` method can cause issues in projects depending on older jackson versions including support-diagnostics as a library.
This PR uses a backwards-compatible method for pretty-printing.
=> Use backwards-compatible pretty-printing

src/main/resources/elastic-rest.yml
Adjust the collection of `_data_stream` to get also hidden/system indices.
This is particularly useful for 8.0 where some system data is in hidden/system data streams instead of normal indices
=> Collect all data streams (including system/hidden ones)

src/main/resources/diags.yml
This adds `dmesg -T` to get absolute time rather than since-boot time as a peer file (`dmesg_t`).
Closes #161
=> Use `dmesg -T` alongside `dmesg`

src/main/resources/kibana-rest.yml
@pmuellr @jportner to better introspect Kibana Security/Space issues, adds APIs into Kibana diagnostic: 
- [List Kibana Roles](https://www.elastic.co/guide/en/kibana/current/role-management-api-get.html)
- [List Kibana Spaces](https://www.elastic.co/guide/en/kibana/current/spaces-api-get-all.html)
- Enables some introspection to mitigate [this](https://github.com/elastic/support-diagnostics/issues/578)'s impact.
- Get Current Kibana User
- URL marks internal, but this is documented [here](https://github.com/elastic/support-diagnostics/issues/479#issuecomment-825148583) & is frequently used to diagnose Kibana permission issues.
Kindly review
1. If endpoints return user private/sensitive data.
2. Initial available versions.
- I pulled via Github search / oldest doc, but there's been a lot …
=> Append Kibana Security APIs

pom.xml, src/main/java/co/elastic/support/BaseConfig.java, src/main/java/co/elastic/support/diagnostics/DiagConfig.java, src/main/java/co/elastic/support/diagnostics/DiagnosticApp.java, src/main/java/co/elastic/support/diagnostics/DiagnosticInputs.java, src/main/java/co/elastic/support/diagnostics/commands/GenerateManifest.java, src/main/java/co/elastic/support/util/SystemProperties.java, src/main/resources/elastic-rest.yml, src/test/java/co/elastic/support/diagnostics/commands/TestKibanaGetDetails.java, src/test/java/co/elastic/support/diagnostics/commands/TestRunKibanaQueries.java, src/test/java/co/elastic/support/rest/TestRestConfigFileValidity.java
This adds the concept of a `runner` to indicate who or what ran the diagnostic, and adds it to the `manifest.json` file.
It also fixes a few things, such as forcing the UTC date functions to actually force UTC, as well as printing the ISO-8601 formatted timezone instead of the RFC 822 ones.
Finally, it fixes a malformed ES action (because it should match one and only one API per action) and removes some Kibana tests that did not reflect the current state of output.
=> Add Runner to Manifest

src/main/resources/elastic-rest.yml
👋🏼 howdy, team! 👶🏼 PR to optimize the [CAT Nodes](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html) response headers
\+ `v` (alias for `version`) - to speed debugging split versions
\- `d` (alias for `disk.avail`) - the question to answer is "is the disk filling up?". With the addition of node temperatures, this has lost its quick-glance meaning.
\+ `dup` (alias for `disk.used_percent`) - this replaces `d` to answer the "is the disk filling up?" question
\- `rp` (alias for `ram.percent` - this is document to be misleading and needing refactored, see [es#32393](https://github.com/elastic/elasticsearch/issues/32393)
\+ current heavy traffic processes [`iic`,`sfc`,`sqc`,`scc`] (aliases for [`indexing.index_current`,`search.fetch_current`, `search.query_current`, …
=> Update CAT Node Headers

src/main/resources/elastic-rest.yml
This adds the `/_internal/_health` _with_ the `explain` parameter.
Closes https://github.com/elastic/support-diagnostics/issues/592
=> [ES] Add `GET /_internal/_health`

src/main/resources/kibana-rest.yml
Add a rest call to the [stack monitoring Health endpoint](https://github.com/elastic/kibana/tree/main/x-pack/plugins/monitoring/server/routes/api/v1/_health)
- `mvn package`
- `unzip target/diagnostics-8.4.1-SNAPSHOT-dist.zip`
- `./target/diagnostics-8.4.1-SNAPSHOT-dist/diagnostics.sh --type kibana-api --host localhost --port 5601 --output ~/OUTPUT_PATH -u elastic -p`
- navigate to OUTPUT_PATH and verify `kibana_stack_monitoring_health.json` is populated
=> [Kibana api] add stack monitoring health api

src/main/resources/elastic-rest.yml
Adds /ml/trained_models and /ml/trained_models/_stats to the
support diag from 7.10 onwards.
These provide details of Java models in 7.x but are particularly
important in 8.0 and above as they provide us with information
about the native PyTorch NLP models that a customer might be
requesting support for.
=> Include ML trained model info in support diag

src/main/java/co/elastic/support/diagnostics/commands/RunKibanaQueries.java, src/main/resources/kibana-rest.yml
When Kibana receives a request for the exception lists, it will return a `404` response if there are no exceptions (even though the API call is valid).
This updates the handling to log the error and move on in that scenario.
=> [Kibana] Fix Broken Endpoints

src/main/resources/elastic-rest.yml
Adds internal state of the desired balance allocator to the diagnostics bundle
(Should be merged after endpoint is commited in ES)
Related to: https://github.com/elastic/elasticsearch/issues/90583
=> [ES] Add `GET /_internal/desired_balance`

src/main/resources/elastic-rest.yml
Update the Health API paths to reflect the latest changes in Elasticsearch 8.6 and 8.7:
1. Starting with 8.6 the `explain` parameter is named `verbose` (I've omitted specifying it as 
the default is `true`)
2. We will promote the API to generally available in 8.7 so the path changed to `_health`
=> [HealthAPI] explain has been renamed to verbose in 8.6 and the API is GA in 8.7

src/main/java/co/elastic/support/monitoring/MonitoringImportConfig.java, src/main/java/co/elastic/support/monitoring/MonitoringImportProcessor.java, src/main/resources/monitoring-extract/templates/monitoring-es-diag.json
With this fix, `import-monitoring` is now able to import data to ESS as follows.
<details>
<summary>import.log</summary>
```shell
C:\Users\YouheiSakurai\git\support-diagnostics\target\diagnostcs\diagnostics-8.4.2-SNAPSHOT>import-monitoring.bat --user elastic -p --port 443 --host 18c**********************dae5d6e.ap-northeast-1.aws.found.io --ssl -i monitoring-export-20221203-060640.zip
No Java Home was found. Using current path. If execution fails please install Java and make sure it is in the search path or exposed via the JAVA_HOME environment variable.
2022-12-03 15:41:43,539 main ERROR Unable to locate appender "diag" for logger config "root"
Processing diagnosticInputs...
Elasticsearch user password: ************************
Deleted directory: …
```
=> Fix bugs in import monitoring

src/main/resources/kibana-rest.yml
Based on https://raw.githubusercontent.com/elastic/kibana/8.0/x-pack/plugins/fleet/common/openapi/bundled.json
None of them are paginated
=> Additional Fleet APIs

README.md, src/main/java/co/elastic/support/monitoring/MonitoringImportInputs.java, src/main/java/co/elastic/support/monitoring/MonitoringImportProcessor.java
**Issue**:
`--indexName` was removed as a part of https://github.com/elastic/support-diagnostics/pull/425, but it's still nice-to-have.
**Solution**:
Revive the option with small alignments.
Closes #537
The option was originally `--indexName`. However, because the target is no longer index but data stream in 8.x as reported in https://github.com/elastic/support-diagnostics/issues/585, I decided to change the option to `--targetsuffix`.
The below console log shows my testing of this change with `diagnostics-8.4.2-SNAPSHOT`. If any further tests are needed, please let me know.
<details>
<summary>Console log running import-monitoring</summary>
```shell
C:\Users\YouheiSakurai\Desktop\diagnostics-8.4.2-SNAPSHOT>import-monitoring.bat -i monitoring-export-20221114-113114.zip --targetsuffix …
```
=> Revive --indexName option to import-monitoring as --targetsuffix

src/main/java/co/elastic/support/diagnostics/commands/RunKibanaQueries.java, src/main/resources/kibana-rest.yml
This removes the Fleet Package Policy API usage from the Kibana diagnostic.
=> [Kibana] Remove Fleet Package Policies

src/main/resources/elastic-rest.yml
Removing `pretty` from the `nodes_stats.json` and `indices_stats.json` we will reduce the frequency of JSON parsing failures in other tools. Anyone working with local files still has the option to use tools like [`jless`](https://github.com/PaulJuliusMartinez/jless), [`fx`](https://github.com/antonmedv/fx) or [`jq`](https://github.com/stedolan/jq) to pretty-print the JSON if needed.
=> Remove `pretty` from nodes/stats and indices/stats

src/main/java/co/elastic/support/diagnostics/commands/RunKibanaQueries.java, src/main/resources/kibana-rest.yml
**Epic:** https://github.com/elastic/kibana/issues/125642
This PR adds the Detection Engine health API implemented in https://github.com/elastic/kibana/pull/157155, to the list of supported endpoints. There was also some cleanup done.
- `/internal/detection_engine/health/_cluster` endpoint is added as `kibana_detection_engine_health_cluster`
- `/internal/detection_engine/health/_space` endpoint is added as `kibana_detection_engine_health_space`
- `kibana_detection_engine_find` renamed to `kibana_detection_engine_rules_installed`
- `kibana_detection_engine_signals` renamed to `kibana_detection_engine_rules_prebuilt_status`
- Added comments, sorted the entries
=> Add Detection Engine health API

README.md, src/main/java/co/elastic/support/monitoring/MonitoringExportService.java, src/main/java/co/elastic/support/monitoring/MonitoringImportInputs.java, src/main/java/co/elastic/support/monitoring/MonitoringImportProcessor.java, src/main/resources/diags.yml, src/main/resources/monitoring-extract/cluster_ids.json, src/main/resources/monitoring-extract/general.json, src/main/resources/monitoring-extract/index_all.json, src/main/resources/monitoring-extract/index_stats.json
resolves #585
~~Differences between 7.x and 8.x:~~
~~- type field is omitted in 8.x~~
~~- cluster_name moves to elasticsearch.cluster.name in 8.x~~
~~- cluster_uuid aliases to elasticsearch.cluster.id in 8.x~~
~~- create action must be used for bulk to data streams in 8.x~~
Differences in monitoring by Metricbeat 8:
- type field is omitted
- cluster_uuid aliases to [*.]elasticsearch.cluster.id
- cluster_name moves to elasticsearch.cluster.name
- bulk with create action to data streams
=> Support export/import of monitoring data from/to 8.x

scripts/diagnostics.bat, scripts/diagnostics.sh, scripts/export-monitoring.bat, scripts/export-monitoring.sh, scripts/import-monitoring.bat, scripts/import-monitoring.sh, scripts/scrub.bat, scripts/scrub.sh
- Unify error message on missing libDir among all scripts
- Unify DIAG_JAVA_OPTS between bat and sh files
- Unify details such as quotation among each type of files
- Port DIAG_DEBUG and related message from sh to bat files
- Change DIAG_JAVA_OPTIONS to DIAG_JAVA_OPTS in bat files
- Add /b option to exit in bat files
<details>
<summary>Test: Run bat files in source</summary>
```console
C:\Users\YouheiSakurai\git\support-diagnostics>scripts\diagnostics.bat --help
Diagnostic executable not found:
Please make sure that you are running with the archive ending with
'-dist.zip' in the name and not the one labeled 'Source code'.
Download at https://github.com/elastic/support-diagnostics/releases/latest
C:\Users\YouheiSakurai\git\support-diagnostics>scripts\import-monitoring.bat --help
Diagnostic …
```
=> Polish scripts

pom.xml
Building the diagnostic analyzer fails on newer JDKs when running the Javadoc task. Upgrading the Javadoc plugin to the current version 3.5.0 fixes the build. As per
https://maven.apache.org/plugins/maven-javadoc-plugin/summary.html, that version of the plugin is still compatible with JDK 8.
=> Upgrade Javadoc plugin to 3.5.0

src/main/resources/elastic-rest.yml
With this commit we add a new API call to gather the status of Universal Profiling in the diagnostic dump. The API is always available in the default distribution even if the Universal Profiling plugin is disabled, so it is always safe to call.
=> Add profiling status API to ES diagnostics

CONTRIBUTING.md
The contribution guide mentioned the unrecognized parameter `-ptp` to specify a password for testing. With this commit we change this to the currently supported parameter `--passwordText` (there is no short variant of this parameter available).
=> Correct password parameter in contribution guide

.github/workflows/publish-release.yml, pom.xml
=> fix: use sha-256 for generating release checksums (#454)

src/main/resources/elastic-rest.yml
These APIs are potentially harmful to large clusters prior to 8.10, see
https://github.com/elastic/elasticsearch/issues/92179.
=> Suppress rollup caps APIs before 8.10.0

src/main/resources/elastic-rest.yml
Basic Stats was introduced in 8.13.0.  It is faster than Transform Stats and will skip checkpointing and other supporting API calls, making it return results more reliably.
------------------------------
Testing:
Ran changes against 8.14 snapshot:
```zsh
local-diagnostics-20240404-210020 git:(main) ✗ ls commercial/transform*
commercial/transform_basic_stats.json  commercial/transform_stats.json
commercial/transform.json
```
```zsh
➜  local-diagnostics-20240404-210020 git:(main) ✗ cat commercial/transform_basic_stats.json | jq '.'
{
"count": 1,
"transforms": [
{
"id": "last-log-from-clientip",
"state": "stopped",
"stats": {
"pages_processed": 0,
"documents_processed": 0,
"documents_indexed": 0,
"documents_deleted": 0,
"trigger_count": 0,
"index_time_in_ms": 0,
"index_total": 0, …
```
=> [Transform] Add basic stats

src/main/resources/elastic-rest.yml
When the output header appears as `role`, chatGPT can decipher what `himrst` means.
```
n                     nodeId m ip           role
tiebreaker-0000000008 lwjY   - 10.46.32.101 mv
instance-0000000001   dNbR   - 10.46.32.174 himrst
instance-0000000000   Xcwh   * 10.46.32.122 himrst
```
=> make cat node output header to be more understandable to both AI and human

src/main/java/co/elastic/support/diagnostics/DiagnosticApp.java, src/main/java/co/elastic/support/monitoring/MonitoringExportApp.java, src/main/java/co/elastic/support/scrub/ScrubApp.java
👋 howdy, team! 
We have users uploading empty (other than `diagnostics.log`) diagnostics to Support. AFAICT most come via the `Fatal error occurred` code path. This PR updates light console formatting to make this failure more obvious to users unfamiliar with our diagnostic (via a line-break and all-caps) so that they can rectify errors before uploading to reduce resolution time. 
TIA! 🙏
=> Make failure error more obvious

pom.xml
Upgrade org.apache.commins:commons-compress to the current latest version (1.26.2) to avoid CVE-2024-25710. Even though I don't believe that the CVE affects this project, it's still better to upgrade to a non-vulnerable version.
=> Upgrade commons-compress to 1.26.2

src/main/java/co/elastic/support/util/ArchiveUtils.java, src/test/java/co/elastic/support/diagnostics/TestDiagnosticService.java
The leading `.` on zip entry names is ignored by (at least) the Mac OS
`unzip` utility which means that every file appears to have an absolute
path, so unpacking a diagnostics bundle emits a warning for every entry:
warning:  stripped absolute path spec from ...
There's no need to prefix every entry name with `./`, so this commit
removes the prefix to avoid these warnings.
=> Remove leading `./` from zip entries

src/main/java/co/elastic/support/diagnostics/commands/RunKibanaQueries.java, src/main/resources/kibana-rest.yml
Adding following API calls from `8.12.0` (we may be able to set a lower minimum version if no sensitive data is returned) :
```
GET kbn:/internal/uptime/service/locations
GET kbn:/api/synthetics/private_locations
GET kbn:/api/uptime/settings
GET kbn:/internal/synthetics/monitor/filters
```
Additionally code for this API was added and API is disabled on purpose pending review that API does not include sensitive information :
```
GET kbn:/internal/synthetics/service/monitors?perPage=100&page=1
```
=> Adding APIs for synthetics

pom.xml
This removes overrides the dependency coming from `httpclient`.
=> [Dependency] Upgrade Commons Codec

src/main/resources/kibana-rest.yml
Data views do help to analyze a Kibana issue. Especially when other APIs collected in the bundle contain only the dataview ID, but not the actual patterns behind that dataview.
=> [Proposal] Collect Kibana dataviews together with Kibana diagnostics

src/main/resources/kibana-rest.yml
Should the requirements for communicating with this API ever change (e.g, we have to specify a header), then we may need to modify it in the future, but for now it works as-is.
Closes https://github.com/elastic/support-diagnostics/issues/676
=> [Kibana] Add Reporting `/internal/reporting/diagnose/browser`

src/main/resources/elastic-rest.yml
Do not get the whole pipeline definition in the Logstash API output.
Only return the Pipeline metadata & params
=> Do not get the whole pipeline definition in the Logstash API output

src/main/resources/logstash-rest.yml
Following https://github.com/elastic/logstash/pull/16520 and consequent https://www.elastic.co/guide/en/logstash/current/health-report-pipeline-flow-worker-utilization.html, I'm adding this API.
FYI @robbavey / @jsvd - I'm adding this API to the Support Diagnostic tool.
Is there any other way to leverage it's output? Should we add something to the Flow visualizer or our Logstash Visualizer?
=> [Logstash] Add Health Report API output

src/main/java/co/elastic/support/diagnostics/commands/BaseQuery.java, src/main/java/co/elastic/support/diagnostics/commands/RunClusterQueries.java, src/main/java/co/elastic/support/diagnostics/commands/RunKibanaQueries.java, src/main/java/co/elastic/support/diagnostics/commands/RunLogstashQueries.java, src/main/java/co/elastic/support/rest/RestClient.java, src/main/java/co/elastic/support/rest/RestEntry.java, src/main/java/co/elastic/support/rest/RestEntryConfig.java, src/main/resources/kibana-rest.yml
Adds functionality to configure headers on a per request statement
Syntax example:
```
<requestname>:
versions:
">= <stackversion>":
url: "<api url"
extra-headers:
<header1>: "<header1value"
<header2>: "<header2value" 
```
e.g.
```
extra-headers:
elastic-api-version: "2023-10-31"
```
Fixes elastic/support-diagnostics#657
=> Add per request functionality to add HTTP request headers

src/main/java/co/elastic/support/diagnostics/commands/CheckElasticsearchVersion.java, src/main/java/co/elastic/support/diagnostics/commands/CheckKibanaVersion.java, src/test/java/co/elastic/support/diagnostics/commands/TestCheckKibanaVersion.java
We came across an issue with failing tests in ECE when the tool is used against pre-release ECE stack versions (e.g. "9.0.0-beta1"). 
We tracked it down to [this semver defect](https://github.com/semver4j/semver4j/issues/307). 
The PR workarounds the problem by removing the pre-release part from version. 
It should not affect the usual workflow though but it can help us to reduce the number of failing tests in CI pipelines until the root cause get fixed.
Closes https://github.com/elastic/support-diagnostics/issues/795
- [] I have verified that the APIs in this pull request do not return sensitive data
Rel: https://elasticco.atlassian.net/browse/CP-10456
=> Workaround for the semver issue with pre-release versions

src/main/resources/elastic-rest.yml
This PR adds [machine learning memory usage collection](https://www.elastic.co/docs/api/doc/elasticsearch/v8/operation/operation-ml-get-memory-stats) to the diagnostics bundle.
=> Add ML memory statistics to the collected diagnostics data

pom.xml
This moves the `maven.compiler.proc` property to the equivalent `proc` element under the maven compiler plugin.
This has no functional change on the build other than to simplify understanding as the property is not used by anything else.
=> [Maven] Move property directly to where it is used

src/main/resources/logstash-diagnostic-templates/flow_metrics.html.ftlh
Prior to this commit, the Logstash Flow Metrics viewer was failing to render with 
```
Uncaught ReferenceError: MaterialUI is not defined
at <anonymous>:9:19
at i (babel.min.js:24:29679)
at r (babel.min.js:24:30188)
at o (babel.min.js:24:30596)
at u (babel.min.js:24:30969)
at f (babel.min.js:1:1812)
at babel.min.js:1:6287
```
error.
=> Fix Logstash Flow metrics viewer
